version: "3.4"
services:
    client: 
        build:
            context: client
            dockerfile: Dockerfile
            args: 
                - REACT_APP_CHAT_API=http://localhost:5000
                - REACT_APP_CHAT_SOCKET_SERVER=http://localhost:5000
        restart: always
        ports:
            - 3000:80
    api:
        build: ./api
        restart: always
        ports: 
            - 5000:5000
        depends_on:
            - db
        environment: 
            - PORT=5000
            - CONNECTION_STRING=mongodb://mongo:27017
    db:
        container_name: mongo
        restart: always
        image: mongo:4.2-bionic
        ports:
            - 27017:27017
